target_architecture:
  platform: linux
  os: centos7
  arch: westmere
compilers:
  - name: 'gcc'
    version: 4.8.5
    system_compiler: true
    flags:
      cflags: -O2 -g
      cxxflags: -O2 -g
      fflags: -O2 -g
  - name: 'gcc'
    version: 9.2.0
    variants:
      - '+piclibs'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=westmere -ftree-vectorize
      cxxflags: -O2 -g -march=westmere -ftree-vectorize
      fflags: -O2 -g -march=westmere -ftree-vectorize
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'gcc'
    version: 6.5.0
    variants:
      - '+piclibs'
    dependencies:
      - '%gcc@4.8.5'
    flags:
      cflags: -O2 -g -march=westmere -ftree-vectorize
      cxxflags: -O2 -g -march=westmere -ftree-vectorize
      fflags: -O2 -g -march=westmere -ftree-vectorize
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'intel-parallel-studio'
    version: 'cluster.2019.3'
    licenses:
      - 'license.lic'
    variants:
      - '+mpi'
    dependencies:
      - '%gcc@9.2.0'
    flags:
      cflags: -O2 -g -march=westmere
      cxxflags: -O2 -g -march=westmere
      fflags: -O2 -g -march=westmere
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'intel-parallel-studio'
    version: 'cluster.2020.0'
    licenses:
      - 'license.lic'
    variants:
      - '+mpi'
    dependencies:
      - '%gcc@9.2.0'
    flags:
      cflags: -O2 -g -march=westmere
      cxxflags: -O2 -g -march=westmere
      fflags: -O2 -g -march=westmere
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
packages:
  - name: 'llvm'
    version: 8.0.0
    extra_flags:
      - '-j 1'
  - name: 'boost'
    version: 1.55.0
  - name: 'cairo'
    version: 1.16.0
  - name: 'ceres-solver'
    version: 1.12.0
  - name: 'chapel'
    version: 1.19.0
  - name: 'cuda'
    version: 10.1.243
  - name: 'cuda'
    version: 10.2.89
  - name: 'ffmpeg'
    version: '4.3'
    variants:
      - '+aom'
      - '+shared'
      - '+x264'
  - name: 'freesurfer'
    version: 6.0.0
    dependencies:
      - '^mesa+opengl+osmesa~llvm'
    licenses:
      - 'license.txt'
  - name: 'freesurfer'
    version: 7.1.0
    dependencies:
      - '^mesa+opengl+osmesa~llvm'
    licenses:
      - 'license.txt'
  - name: 'go'
    version: 1.12.8
    dependencies:
      - '^git@2.21.0'
  - name: 'go'
    version: 1.14.7
    dependencies:
      - '^git@2.21.0'
  - name: 'heaptrack'
    version: 1.1.0
  - name: 'intel-mkl'
    version: 2019.3.199
    variants:
      - 'threads=openmp'
  - name: 'miniconda2'
    version: 4.6.14
  - name: 'miniconda3'
    version: 4.6.14
  - name: 'motif'
    version: 2.3.8
  - name: 'opencv'
    version: 4.1.0
    variants:
      - '~cuda'
      - '~vtk'
      - '~openmp'
      - 'arch=linux-centos7-westmere'
    dependencies:
      - '^ffmpeg@4.1.1'
  - name: 'openfoam'
    version: '1906'
    variants:
      - '+metis'
      - '+scotch'
      - '+mgridgen'
  - name: 'openfoam-org'
    version: '7'
    variants:
      - '+metis'
  - name: 'openfoam-org'
    version: '8'
    variants:
      - '+metis'
  - name: 'openmpi'
    version: 3.1.4
  - name: 'openmpi'
    version: 1.6.5
  - name: 'magma'
    version: 2.5.3
    dependencies:
      - '%gcc@6.5.0'
      - '^cmake%gcc@9.2.0'
      - '^cuda%gcc@9.2.0'
      - '^openblas%gcc@9.2.0'
  - name: 'python'
    version: 3.7.4
  - name: 'r'
    version: 3.6.1
  - name: 'r'
    version: 3.6.3
  - name: 'r-irkernel'
    version: '1.1'
  - name: 'r-tidyverse'
    version: '1.3.0'
  - name: 'r-triton'
    version: '1.0.0'
  - name: 'py-gpaw'
    version: 1.3.0
    variants:
      - '+fftw'
      - '+mpi'
      - '+scalapack'
    dependencies:
      - '^py-ase@3.18.0'
  - name: 'py-gpaw'
    version: 19.8.1
    variants:
      - '+fftw'
      - '+mpi'
      - '+scalapack'
    dependencies:
      - '^py-ase@3.18.0'
  - name: 'py-gpaw'
    version: 20.1.0
    variants:
      - '+fftw'
      - '+mpi'
      - '+scalapack'
    dependencies:
      - '^py-ase@3.19.0'
  - name: 'scorep'
    version: '6.0'
    variants:
      - '+mpi'
      - '+papi'
      - '+pdt'
      - '+cuda'
  - name: 'texlive'
    version: 'live'
  - name: 'upcxx'
    version: 2019.3.2
  - name: 'valgrind'
    version: 3.15.0
  - name: 'gcc'
    version: '9.2.0'
    variants:
      - '+piclibs'
      - '+nvptx'
  - name: 'intel-parallel-studio'
    version: 'cluster.2020.0'
    variants:
      - '~mpi'
    licenses:
      - 'license.lic'
    target_architecture:
      platform: linux
      os: centos7
      arch: x86_64
  - name: 'cp2k'
    version: '6.1'
    variants:
      - 'blas=openblas'
      - '~cuda'
      - '+mpi'
      - '+openmp'
  - name: 'cp2k'
    version: '6.1'
    variants:
      - 'blas=openblas'
      - '~cuda'
      - '+mpi'
      - '~openmp'
  - name: 'cp2k'
    version: '6.1'
    variants:
      - 'blas=openblas'
      - '+cuda'
      - '+mpi'
      - '+openmp'
      - '+cuda_blas'
      - '+cuda_fft'
      - 'cuda_arch=37'
      - '%gcc@6.5.0'
  - name: 'cp2k'
    version: '6.1'
    variants:
      - 'blas=openblas'
      - '+cuda'
      - '+mpi'
      - '+openmp'
      - '+cuda_blas'
      - '+cuda_fft'
      - 'cuda_arch=60'
      - '%gcc@6.5.0'
  - name: 'cp2k'
    version: '6.1'
    variants:
      - 'blas=openblas'
      - '+cuda'
      - '+mpi'
      - '+openmp'
      - '+cuda_blas'
      - '+cuda_fft'
      - 'cuda_arch=70'
      - '%gcc@6.5.0'
  - name: 'hdf5'
    version: 1.10.5
    variants:
      - '+fortran'
      - '+hl'
      - '+mpi'
      - '+pic'
  - name: 'boost'
    version: 1.70.0
    variants:
      - '+mpi'
      - '+pic'
  - name: 'emacs'
    version: '26.2'
  - name: 'glew'
    version: 2.1.0
    dependencies:
      - '^mesa+opengl+osmesa~llvm'
  - name: 'nvtop'
    version: 1.0.0
    dependencies:
      - '%gcc@6.5.0'
  - name: 'git-lfs'
    version: 2.11.0
  - name: 'vim'
    version: 8.1.0338
    variants:
      - '+huge'
  - name: 'ior'
    version: 3.2.0
    variants:
      - '+hdf5'
      - '+ncmpi'
  - name: 'pigz'
    version: '2.4'
  - name: 'fzf'
    version: '0.17.5'
    dependencies:
      - '^git@2.21.0'
  - name: 'abinit'
    version: '8.10.3'
    variants:
      - '+mpi'
      - '+openmp'
      - '+scalapack'
